<?php
class Account_Domain_Account_ValueObject_Password
{
    /**
     * @var string
     */
    private $_password;
    
    /**
     * @var boolean
     */
    private $_isEncoded;
    
    /**
     * @var boolean
     */
    private $_isAutoGenerated;
    
    /**
     * @param string $password
     * @param boolean $isEncoded
     */
    public function __construct($password, $isEncoded = false, $isAutoGenerated = false)
    {
        $this->_password = $password;
        $this->_isEncoded = $isEncoded;
        $this->_isAutoGenerated = $isAutoGenerated;
    }
    
    /**
     * @return string
     */
    public function getPassword()
    {
        return $this->_password;
    }
    
    /**
     * @return boolean
     */
    public function isEncoded()
    {
        return $this->_isEncoded;
    }
    
    /**
     * @return boolean
     */
    public function isAutoGenerated()
    {
        return $this->_isAutoGenerated;
    }
    
    /**
     * Return encoded password
     * 
     * @return Account_Domain_Account_ValueObject_Password
     */
    public function getEncoded()
    {
       
        if(!$this->_isEncoded){
            return new Account_Domain_Account_ValueObject_Password(
                sha1($this->_password),
                true,
                $this->_isAutoGenerated
            );
        } else {
            return new Account_Domain_Account_ValueObject_Password($this->_password, $this->_isEncoded, $this->_isAutoGenerated);
        }
    }
    
    /**
     * @return string
     */
    public function __toString()
    {
        return $this->_password;
    }
}