<?php
interface MySecureAccount_WebService_Account_General_V1r0_GeneralInterface
{
	/**
     * Create new account
     * 
     * $ownerInformation keys:
     *  - string $firstName
     *  - string $lastName
     *  - string $dateOfBirth
     *  - string $gender
     *  - string $nickName
     *  - string $mobileNumber
     *  - string $homeNumber
     *  - string $additionalInformation
     *  
     * $deliveryInformation keys:
     *  - string $country
     *  - string $city
     *  - string $postCode
     *  - string $street
     *  - string $houseNumber
     *  - string $secondAddressLine
     *  - string $thirdAddressLine
     *  - string $additionalInformation 
     *  
     * $settings keys:
     *  - locale keys:
     *    - array country 
     *       - string code
     *       - string title
     *    - array language 
     *       - string code
     *       - string title
     * 
     * @param string $customerEmail
     * @param string $password
     * @param string $passwordAgain
     * @param array $ownerInformation
     * @param array $deliveryInformation
     * @param array $settings
     * @param boolean $passwordAutoGenerated
     * 
     * @return void
     */
    public function setupAccount(
        $customerEmail, 
        $password, 
        $passwordAgain, 
        array $ownerInformation = array(),
        array $deliveryInformation = array(),
        array $settings = array(),
        $passwordAutoGenerated = false
    );
    
    /**
     * Activate account by confirmg primary email address
     * 
     * @param string $customerEmail
     * @param string $activationKey
     * 
     * @return void
     */
    public function activateAccount($customerEmail, $activationKey);
    
    /**
     * Authenticate customer
     *
     * @param string $customerEmail
     * @param string $password
     * 
     * @return void
     */
    public function login($customerEmail, $password);

    /**
     * Logout customer
     * 
     * @param string $customerEmail
     * 
     * @return void
     */
    public function logout($customerEmail);

    /**
     * Reset password
     * @param string $customerEmail
     * 
     * @return void
     */
    public function remindPassword($customerEmail);

    /**
     * Remind email activation key
     * 
     * @param string $customerEmail
     * 
     * @return void
     */
    public function remindActivationKey($customerEmail);
    
    /**
     * Delete account
     * 
     * @param string $customerEmail
     * 
     * @return void
     */
    public function deleteAccount($customerEmail);

    /**
     * Change password
     * 
     * @param string $customerEmail
     * @param string $password
     * 
     * @return void
     */
    public function changePassword($customerEmail, $password);

    /**
     * Update customer details (Array structure see at setupAccount doc block)
     * 
     * @param string $customerEmail
     * @param array $customerDetails
     * 
     * @return void
     */
    public function updateCustomerDetails($customerEmail, array $customerDetails);
    
    /**
     * Update customer delivery details (Array structure see at setupAccount doc block)
     * 
     * @param string $customerEmail
     * @param array $customerDeliveryDetails
     */
    public function updateCustomerDeliveryDetails($customerEmail, array $customerDeliveryDetails);

    
    /**
     * Create new products in account
     * 
     * Available product names:
     *  - my-theft-protection
     *  - my-mobile-theft-protection
     * 
     * $products:
     *  array(
     *      'my-theft-protection' =>
     *      array(
     *          'my-theft-protection',
     *          'MyTheftProtection title',
     *          '1', // version
     *          '12', // duration
     *          'license-2', // license code
     *          'full', // license type
     *          array() // additional things
     *      ),
     *  )
     *   
     * @param string $email
     * @param array $products
     * 
     * @return void
     */
    public function addNewProductsInAccount($customerEmail, array $products);
      
    /**
     * Create new devices
     * If email address is passed it will be assigned to account
     * 
     * array(
     *      'iphone' => array(
     *           'deviceName' => 'iphone',
     *           'deviceTitle' => 'With spaces',
     *           'deviceType' => 'MOBILE', // getConstants()
     *           'operatingSystem' => 'NA', // getConstants()
     *           'operatingSystemType' => 'NA', // getConstants()
     *           'settings' => array(
     *               'my-mobile-theft-protection' => array(
     *                   'settings' => '<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><Settings/>'
     *               ),
     *           ),
     *       ),
     *       'laptop' => array(
     *           'deviceName' => 'laptop',
     *           'deviceTitle' => 'With spaces',
     *           'deviceType' => 'LAPTOP', // getConstants()
     *           'operatingSystem' => 'WINDOWS', // getConstants()
     *           'operatingSystemType' => 'OS_64', // getConstants()
     *           'settings' => array(
     *           ),
     *       ),
     *   )
     * 
     * @param string $customerEmail
     * @param array $devices
     * 
     * @return void
     */
    public function addNewDevicesInAccount($customerEmail, array $devices);

    /**
     * Updated device details
     * 
     * 'deviceTitle' => 'With spaces',
     * 'deviceType' => 'MOBILE', // getConstants()
     * 'operatingSystem' => 'NA', // getConstants()
     * 'operatingSystemType' => 'NA', // getConstants()
     * 
     * @param string $customerEmail
     * @param string $deviceName
     * @param array $deviceDetails
     * 
     * @return void
     */
    public function updateDeviceDetails($customerEmail, $deviceName, array $deviceDetails);
    
    /**
     * Delete device
     * 
     * @param string $customerEmail
     * @param string $deviceName
     * 
     * @return void
     */
    public function deleteDevice($customerEmail, $deviceName);
    
    /**
     * Install product on device
     * 
     * Installation settings for mobile anti-theft
     * 
     * 'my-mobile-theft-protection' => array(
     *   'deviceNumber' => '00370682575465',
     *   'devicePin' => '1234',
     *   'settings' => '<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><Settings/>'
     * ),
     * 
     * @param string $customerEmail
     * @param string $deviceName
     * @param string $productName
     * @param string $license
     * @param array $settings
     * 
     * @return void
     */
    public function installProductOnDevice(
        $customerEmail, 
        $deviceName, 
        $productName, 
        $license, 
        array $settings = array()
    );
    
    /**
     * Uninstall product from device
     * 
     * @param string $customerEmail
     * @param string $deviceName
     * @param string $productName
     * @param string $license
     * @param array $settings (optional)
     * 
     * @return void
     */
    public function uninstallProductFromDevice(
        $customerEmail, 
        $deviceName, 
        $productName,
        array $settings = array()
    );
    
    /**
     * Reinstall product from device
     * 
     * @param string $customerEmail
     * @param string $deviceName
     * @param string $productName
     * @param array $settings
     * 
     * @return void
     */
    public function reinstallProductOnDevice(
        $customerEmail, 
        $deviceName, 
        $productName,
        array $settings = array()
    );
        
    /**
     * Move product installation from device A to device B
     * 
     * @param string $customerEmail
     * @param string $fromDeviceName
     * @param string $toDeviceName
     * @param string $productName
     * @param string $license
     * @param array $settings (optional)
     * 
     * @return void
     */
    public function transferProductInstallation(
        $customerEmail, 
        $fromDeviceName, 
        $toDeviceName, 
        $productName,
        array $settings = array()
    );
    
    /**
     * @param string $customerEmail
     * @param string $deviceName
     * @param array $settings
     * 
     * @return void
     */
    public function changeDeviceDefaultSettings(
        $customerEmail, 
        $deviceName, 
        array $settings
    );
    
    /**
     * Return account information
     * 
     * @param string $customerEmail
     * 
     * @return array
     */
    public function getAccountInformation($customerEmail);
        
	/**
     * Get products list
     * 
     * array(
     *       'my-mobile-theft-protection' => array(
     *           'product_data' => array(
     *               'title' => '<strong>MY</strong>Mobile TheftProtection',
     *               'name' => 'my-mobile-theft-protection',
     *           ),
     *           'licenses' => array(
     *               'used' => array(
     *                   'dummy-license-1-mtp'
     *               ),
     *               'free' => array(
     *
     *               )
     *           ),
     *           'devices' => array(
     *               'nokia-3520' => array(
     *                   'name'             => 'nokia-3520',
     *                   'title'            => 'Nokia 3520',
     *                   'deviceType'       => 'UNIVERSAL',
     *                   'deviceOS'         => 'SYMBIAN',
     *                   'deviceOSType'     => '',
     *                   'devicePin'        => '9966',
     *                   'subscriptionType' => 'FULL',
     *                   'number'           => '006126564561898',
     *                   'deviceId'         => 'uniqueId1'
     *               ),
     *           )
     *       ),
     *   );
     * 
     * @param string $customerEmail
     * @param array $tags
     * 
     * @return array
     */
    public function getAccountProductsInformation($customerEmail, array $tags = array());
  
    
    /**
     * Get devices list
     * 
     * array(
     *       'nokia-3520' => array(
     *           'device_data' => array(
     *               'name'             => 'nokia-3520',
     *               'title'            => 'Nokia 3520',
     *               'deviceType'       => 'UNIVERSAL',
     *               'deviceOS'         => 'SYMBIAN',
     *               'deviceOSType'     => '',
     *               'devicePin'        => '9966',
     *               'subscriptionType' => 'FULL',
     *               'number'           => '006126564561898',
     *               'deviceId'         => 'uniqueId1'
     *           ),
     *           'products_data' => array(
     *               'my-mobile-theft-protection' => array(
     *                   'name' => 'my-mobile-theft-protection',
     *                   'title' => '<strong>MY</strong>Mobile TheftProtection',
     *                   'license' => 'dummy-license-1-mtp'
     *               )
     *           )
     *       ),
     *       'htc-hd2' => array(
     *          'device_data' => array(
     *               'name'             => 'htc-hd2',
     *               'title'            => 'HTC HD2',
     *               'deviceType'       => 'MOBILE',
     *               'deviceOS'         => 'WINDOWS',
     *               'deviceOSType'     => '',
     *               'devicePin'        => '1234',
     *               'subscriptionType' => 'FULL',
     *               'number'           => '987654321',
     *               'deviceId'         => 'uniqueId2'
     *           ),
     *           'products_data' => array(
     *           )
     *       ),
     *       'sample-phone' => array(
     *           'device_data' => array(
     *               'name'             => 'sample-phone',
     *               'title'            => 'Sample phone',
     *               'deviceType'       => 'MOBILE',
     *               'deviceOS'         => 'BLACKBERRY',
     *              'deviceOSType'     => '',
     *               'devicePin'        => '6969',
     *               'subscriptionType' => 'FULL',
     *               'number'           => '555522233',
     *               'deviceId'         => 'uniqueId3'
     *           ),
     *           'products_data' => array(
     *           )
     *       ),
     *   );
     * 
     * @param string $customerEmail
     * @param array $tags
     * 
     * @return array
     */
    public function getAccountDevicesInformation($customerEmail, array $tags = array());
    
    /**
     * Return available constants
     * 
     * @return array
     */
    public function getConstants();
}