<?php
namespace Shop\AppServices\Write; 

class ShopService 
{
    public function requestForCart()
    {
    	/**
    	 * Here should not be anything else
    	 * because everything should be solved in domain
    	 * 
	    	$command = Oxy_Cqrs_Command_CommandAbstract::factory(
	            'MySecureAccount_Lib_Command_DoSetupAccount', 
	            array(
	                $accountGuid,
	                $email,
	                $email,
	                $password,
	                $passwordAgain,
	                $passwordAutoGenerated,
	                $ownerInformation,
	                $deliveryInformation,
	                array($settings)
	            )
	        );  
	        
	        $this->_queue->addCommand($command); 
	     *    
         **/  	
    }

    public function giveAwayCart()
    {
    }

    public function checkoutCart()
    {
    }

    public function addProductToCart()
    {
    }

    public function removeProductFromCart()
    {
    }

    public function replaceProductInCart()
    {
    }
}
